AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Store and restore backup functionality
Resources:
  RequireIDBackupLoad:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./app/src/handlers
      Handler: backup.load.run
      Events:
        RequrieIDLoad:
          Type: Api
          Properties:
            Path: /backup/load
            Method: GET
  RequireIDBackupStore:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./app/src/handlers
      Handler: backup.store.run
      Events:
        RequrieIDLoad:
          Type: Api
          Properties:
            Path: /backup/store
            Method: POST
  RequireIDBackupDelete:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./app/src/handlers
      Handler: backup.delete.run
      Events:
        RequrieIDLoad:
          Type: Api
          Properties:
            Path: /backup/delete
            Method: POST
  RequireIDAppPoll:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./app/src/handlers
      Handler: app.poll.run
      Events:
        RequrieIDLoad:
          Type: Api
          Properties:
            Path: /app/poll
            Method: GET
  RequireIDAppResponse:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./app/src/handlers
      Handler: app.response.run
      Events:
        RequrieIDLoad:
          Type: Api
          Properties:
            Path: /app/response
            Method: POST
  RequireIDPromptNew:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./app/src/handlers
      Handler: prompt.new.run
      Events:
        RequrieIDLoad:
          Type: Api
          Properties:
            Path: /prompt/new
            Method: POST
  RequireIDPromptPoll:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./app/src/handlers
      Handler: prompt.poll.run
      Events:
        RequrieIDLoad:
          Type: Api
          Properties:
            Path: /prompt/poll
            Method: GET
  RequireIDPromptAbort:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      CodeUri: ./app/src/handlers
      Handler: prompt.abort.run
      Events:
        RequrieIDLoad:
          Type: Api
          Properties:
            Path: /prompt/abort
            Method: POST
