AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: require.id API
Metadata:
  AWS::ServerlessRepo::Application:
    Name: require-id
    Description: require.id API
    Author: require-id
    HomePageUrl: https://require.id/
    SourceCodeUrl: https://github.com/require-id
Resources:
  RequireIDAPIGatewayExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: execution
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: '*'
  RequireIDGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      EndpointConfiguration: EDGE
      DefinitionBody:
        openapi: 3.0.1
        info:
          version: "0.0.0"
          title: require.id API
          description: require.id API
        x-amazon-apigateway-api-key-source: HEADER
        components:
          securitySchemes:
            ApiKeyAuth:
              type: apiKey
              name: x-api-key
              in: header
        paths:
          /api/status:
            x-amazon-apigateway-auth:
              type: NONE_KEY
            get:
              security:
              - ApiKeyAuth: []
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
                security:
                - ApiKeyAuth: []
          /app/poll:
            x-amazon-apigateway-auth:
              type: NONE_KEY
            get:
              security:
              - ApiKeyAuth: []
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
                security:
                - ApiKeyAuth: []
          /app/response:
            x-amazon-apigateway-auth:
              type: NONE_KEY
            post:
              security:
              - ApiKeyAuth: []
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
                security:
                - ApiKeyAuth: []
          /app/subscribe:
            x-amazon-apigateway-auth:
              type: NONE_KEY
            post:
              security:
              - ApiKeyAuth: []
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
                security:
                - ApiKeyAuth: []
          /backup/store:
            x-amazon-apigateway-auth:
              type: NONE_KEY
            post:
              security:
              - ApiKeyAuth: []
              parameters:
              - name: proxy
                in: path
                required: true
                type: string
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
                security:
                - ApiKeyAuth: []
          /backup/load:
            x-amazon-apigateway-auth:
              type: NONE_KEY
            get:
              security:
              - ApiKeyAuth: []
              parameters:
              - name: proxy
                in: path
                required: true
                type: string
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
                security:
                - ApiKeyAuth: []
          /backup/delete:
            x-amazon-apigateway-auth:
              type: NONE_KEY
            delete:
              security:
              - ApiKeyAuth: []
              parameters:
              - name: proxy
                in: path
                required: true
                type: string
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
                security:
                - ApiKeyAuth: []
          /prompt/new:
            post:
              parameters:
              - name: proxy
                in: path
                required: true
                type: string
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
          /prompt/poll:
            get:
              parameters:
              - name: proxy
                in: path
                required: true
                type: string
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
          /prompt/abort:
            delete:
              parameters:
              - name: proxy
                in: path
                required: true
                type: string
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequireIDLambda.Arn}/invocations"
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
                credentials: !GetAtt RequireIDAPIGatewayExecutionRole.Arn
  RequireIDApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - RequireIDUsagePlan
    Properties:
      Name: RequireIDApiKey
      Enabled: "true"
      StageKeys:
        - RestApiId: !Ref RequireIDGateway
          StageName: !Ref RequireIDGateway.Stage
  RequireIDUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - RequireIDGateway
    Properties:
      ApiStages:
      - ApiId: !Ref RequireIDGateway
        Stage: !Ref RequireIDGateway.Stage
      UsagePlanName: RequireIDUsagePlan
  RequireIDUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties :
      KeyId: !Ref RequireIDApiKey
      UsagePlanId: !Ref RequireIDUsagePlan
      KeyType: API_KEY
  RequireIDLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: router.run
      Events:
        ApiStatus:
          Type: Api
          Properties:
            Path: /api/status
            RestApiId: !Ref RequireIDGateway
            Method: GET
        AppPoll:
          Type: Api
          Properties:
            Path: /app/poll
            RestApiId: !Ref RequireIDGateway
            Method: GET
        AppResponse:
          Type: Api
          Properties:
            Path: /app/response
            RestApiId: !Ref RequireIDGateway
            Method: POST
        AppSubscribe:
          Type: Api
          Properties:
            Path: /app/subscribe
            RestApiId: !Ref RequireIDGateway
            Method: POST
        BackupStore:
          Type: Api
          Properties:
            Path: /backup/store
            RestApiId: !Ref RequireIDGateway
            Method: POST
        BackupLoad:
          Type: Api
          Properties:
            Path: /backup/load
            RestApiId: !Ref RequireIDGateway
            Method: GET
        BackupDelete:
          Type: Api
          Properties:
            Path: /backup/delete
            RestApiId: !Ref RequireIDGateway
            Method: DELETE
        PromptNew:
          Type: Api
          Properties:
            Path: /prompt/new
            RestApiId: !Ref RequireIDGateway
            Method: POST
        PromptPoll:
          Type: Api
          Properties:
            Path: /prompt/poll
            RestApiId: !Ref RequireIDGateway
            Method: GET
        PromptAbort:
          Type: Api
          Properties:
            Path: /prompt/abort
            RestApiId: !Ref RequireIDGateway
            Method: DELETE
