AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: require.id API
Metadata:
  AWS::ServerlessRepo::Application:
    Name: require-id
    Description: require.id API
    Author: require-id
    HomePageUrl: https://require.id/
    SourceCodeUrl: https://github.com/require-id
Resources:
  RequireID:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: index.run
      Events:
        BackupLoad:
          Type: Api
          Properties:
            Path: /backup/load
            Method: GET
        BackupStore:
          Type: Api
          Properties:
            Path: /backup/store
            Method: POST
        BackupDelete:
          Type: Api
          Properties:
            Path: /backup/delete
            Method: POST
        AppPoll:
          Type: Api
          Properties:
            Path: /app/poll
            Method: GET
        AppResponse:
          Type: Api
          Properties:
            Path: /app/response
            Method: POST
        PromptNew:
          Type: Api
          Properties:
            Path: /prompt/new
            Method: POST
        PromptPoll:
          Type: Api
          Properties:
            Path: /prompt/poll
            Method: GET
        PromptAbort:
          Type: Api
          Properties:
            Path: /prompt/abort
            Method: POST
